### ISSUE TITLE
not responding

### ISSUE THREAD

**Issue by 359189854** [squid-box/SevenZipSharp#27]
var extractor = new SevenZipExtractor(@"test.rar");
            for (var i = 0; i < extractor.ArchiveFileData.Count; i++)
            {
                extractor.ExtractFiles("bb", extractor.ArchiveFileData[i].Index);
            }

not responding at last file?

**Comment by squid-box** [comment]
I have no problems running that code snippet, you'll have to provide more information if I'm to help you.

How does `test.rar` look? I'm assuming multiple files. Is it a RAR4 or RAR5 format archive? Anything special about it?

Is there any particular reason you're iterating over all files by index, rather than just calling eg. `extractor.ExtractArchive("bb");`?

**Comment by squid-box** [comment]
With no reply in almost a month I'm closing the issue.

Reopen it if you have more info.
