### ISSUE TITLE
targeting .net standard?

### ISSUE THREAD

**Issue by CasperWSchmidt** [squid-box/SevenZipSharp#28]
Hi

Any plans on targeting .Net standard 2.0?

**Comment by squid-box** [comment]
No plans from my side, but I'm not dismissing the idea either. I simply haven't had the need for it (yet).

If you want to suggest an approach to do it, I'm all ears :)

**Comment by CasperWSchmidt** [comment]
Hi. As mentioned in #29 I currently use another fork of SevenZipSharp that supports .Net Standard (1.3 though - but that is good enough for me). See https://github.com/antiufo/SevenZipSharp/commit/34510abcc3d1ab79b76ff6fd692d6f08ca2e1ff7 for changes neccesary. I can make a PR with this, but will wait for the fork-owner to get back (I e-mailed her)

**Comment by squid-box** [comment]
I've had a quick look, and while it does seem manageable, there's some extra work on my branch since I've included the SFX creation code as well. I won't have time to do it right now, but I'll revisit it sometime soon-ish.

This issue might not matter much to you anyway, pending the resolution of #29.

If you do make a PR, I'll make time to look it through, and will likely accept it (might modify it to include both .NET 4.5 and .NET Standard 2.0 in the NuGet package.

**Comment by Kaon68** [comment]
I would appreciate the .NET Standard compatibility of this fork too :D
I have a library in .NET Standard where code for create and read archive is (but the main program using this library is in .NET 4.6.2). I use SevenZipSharp from Shaman, but it lacks updates from many months. 

I follows this issue ;)

**Comment by squid-box** [comment]
@CasperWSchmidt & @Kaon68 

Sorry, I forgot about this issue. As of 1.2.x this project provides dll's for both .NET 4.5 and Standard 2.0.

If it's still relevant, please check it out and see if it works for you.

**Comment by CasperWSchmidt** [comment]
I convinced the sender to change the format from RAR to ZIP which allowed me to use another library :)

**Comment by squid-box** [comment]
Happy you found a work-around, thanks for responding :)
